# Generated by Django 5.2.2 on 2025-06-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_skill_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_tags',
        ),
        migrations.AddField(
            model_name='project',
            name='project_tags',
            field=models.ManyToManyField(related_name='projects', to='main_app.projecttag'),
        ),
    ]
