# Generated by Django 5.2.2 on 2025-06-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_projecttag_project_project_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_projects',
            field=models.BooleanField(default=False),
        ),
    ]
